#!/bin/bash
PROJECT_HOME="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
cd "${PROJECT_HOME}" || exit 1
. "./scripts/inc-sh/common-pre.inc.sh"
require_root_or_exit

main_func()
{
	apt-get -y install git

	hostname="$(hostname 2>/dev/null || cat /etc/hostname)"
	hostname="${hostname%%.*}"
	dnsdomainname="$(dnsdomainname 2>/dev/null || true)"
	if [ -n "${dnsdomainname}" ]; then
		hostname="${hostname}.${dnsdomainname}"
	fi

	if [ -z "${USER:-}" ]; then
		USER="$(whoami)"
	fi

	git_name="$( git config --global --get 'user.name' )"
	git_email="$( git config --global --get 'user.email' )"

	if [ -z "${git_name}" ] && [ -z "${git_email}" ] ; then
		git config --global 'user.name' "${USER}"
		git config --global 'user.email' "${USER}@${hostname}"
	fi

	true
}

. "./scripts/inc-sh/common-run-main.inc.sh"
. "./scripts/inc-sh/common-post.inc.sh"
