#!/bin/bash
PROJECT_HOME="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
cd "${PROJECT_HOME}" || exit 1
source "./scripts/inc-sh/common-pre.inc.sh"
require_root_or_exit

main_func()
{
	if ! [ -d /etc/logrotate.d ] ; then
		install -v -d -m 0755 -o root -g root /etc/logrotate.d
	fi

	install -v -m 0644 -o root -g root \
		./files/system/etc/logrotate.d/100-local-dateext \
		/etc/logrotate.d/100-local-dateext

}

source "./scripts/inc-sh/common-run-main.inc.sh"
source "./scripts/inc-sh/common-post.inc.sh"
