#!/bin/bash
PROJECT_HOME="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
cd "${PROJECT_HOME}"
source "./scripts/inc-sh/common-pre.inc.sh"
require_root_or_exit

main_func()
{
	local ret_val=1

	TEMP_DIR="$( mktemp -d )"
	cp -v -a /root/.bashrc "${TEMP_DIR}/.bashrc"
	cp -v -a "files/system/root/bashrc.patch" "${TEMP_DIR}/bashrc.patch"

	ls -la "${TEMP_DIR}"

	patch -N -p 1 --fuzz=0 -d "${TEMP_DIR}" -i "${TEMP_DIR}/bashrc.patch"
	ret_val=$?

	if [ "${ret_val}" -eq 0 ] ; then
		install -v -C -m 0644 -o root -g root \
			"${TEMP_DIR}/.bashrc" \
			/root/.bashrc
		ret_val=$?
	fi

	rm -rf "${TEMP_DIR}"

	return "${ret_val}"
}

source "./scripts/inc-sh/common-run-main.inc.sh"
source "./scripts/inc-sh/common-post.inc.sh"
