#!/bin/bash
PROJECT_HOME="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
cd "${PROJECT_HOME}" || exit 1
source "./scripts/inc-sh/common-pre.inc.sh"
require_root_or_exit

main_func()
{
	sed -i \
		-e 's/^#\s*\(en_CA.UTF-8\)/\1/' \
		-e 's/^#\s*\(en_GB.UTF-8\)/\1/' \
		-e 's/^#\s*\(en_IE.UTF-8\)/\1/' \
		-e 's/^#\s*\(en_US.UTF-8\)/\1/' \
		-- /etc/locale.gen

	dpkg-reconfigure -f noninteractive locales

	update-locale LANG="en_CA.UTF-8" LANGUAGE="en_CA:en"

	# Load apt files with translations
	apt-get -y update

	true
}

source "./scripts/inc-sh/common-run-main.inc.sh"
source "./scripts/inc-sh/common-post.inc.sh"
