#!/bin/bash
PROJECT_HOME="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
cd "${PROJECT_HOME}"
source "./scripts/inc-sh/common-pre.inc.sh"
require_root_or_exit

main_func()
{
	apt-get -y install ncdu
	apt-get -y install tree
	apt-get -y install p7zip-full
	apt-get -y install htop
	apt-get -y install pinfo
	apt-get -y install screen
	apt-get -y install tmux

	true
}

source "./scripts/inc-sh/common-run-main.inc.sh"
source "./scripts/inc-sh/common-post.inc.sh"
