#!/bin/bash
PROJECT_HOME="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
cd "${PROJECT_HOME}" || exit 1
. "./scripts/inc-sh/common-pre.inc.sh"
require_root_or_exit

main_func()
{
	sed -i \
		-e 's/^#\s*\(fr_CA.UTF-8\)/\1/' \
		-e 's/^#\s*\(fr_FR.UTF-8\)/\1/' \
		-- /etc/locale.gen

	dpkg-reconfigure -f noninteractive locales

	true
}

. "./scripts/inc-sh/common-run-main.inc.sh"
. "./scripts/inc-sh/common-post.inc.sh"
